search: my_socket.h board.h OTP.h search.cpp
	g++ -std=c++11 -O2 -Wall search.cpp -o search
judge: my_socket.h board.h judge.cpp
	g++ -std=c++11 -O2 -Wall judge.cpp -o judge
http: my_socket.h board.h OTP.h simple_http_UI.cpp
	g++ -std=c++11 -O2 -Wall simple_http_UI.cpp -o simple_http_UI

